services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always
